# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage_controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StageControlWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 282)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonforward = QtWidgets.QPushButton(self.centralwidget)
        self.buttonforward.setGeometry(QtCore.QRect(80, 40, 61, 61))
        self.buttonforward.setObjectName("buttonforward")
        self.buttonleft = QtWidgets.QPushButton(self.centralwidget)
        self.buttonleft.setGeometry(QtCore.QRect(10, 110, 61, 61))
        self.buttonleft.setObjectName("buttonleft")
        self.buttonright = QtWidgets.QPushButton(self.centralwidget)
        self.buttonright.setGeometry(QtCore.QRect(150, 110, 61, 61))
        self.buttonright.setObjectName("buttonright")
        self.buttondown = QtWidgets.QPushButton(self.centralwidget)
        self.buttondown.setGeometry(QtCore.QRect(230, 150, 61, 61))
        self.buttondown.setObjectName("buttondown")
        self.buttonback = QtWidgets.QPushButton(self.centralwidget)
        self.buttonback.setGeometry(QtCore.QRect(80, 180, 61, 61))
        self.buttonback.setObjectName("buttonback")
        self.buttonup = QtWidgets.QPushButton(self.centralwidget)
        self.buttonup.setGeometry(QtCore.QRect(230, 70, 61, 61))
        self.buttonup.setObjectName("buttonup")
        self.xmminput = QtWidgets.QTextEdit(self.centralwidget)
        self.xmminput.setGeometry(QtCore.QRect(360, 90, 151, 21))
        self.xmminput.setObjectName("xmminput")
        self.ymminput = QtWidgets.QTextEdit(self.centralwidget)
        self.ymminput.setGeometry(QtCore.QRect(360, 130, 151, 21))
        self.ymminput.setObjectName("ymminput")
        self.zmminput = QtWidgets.QTextEdit(self.centralwidget)
        self.zmminput.setGeometry(QtCore.QRect(360, 170, 151, 21))
        self.zmminput.setObjectName("zmminput")
        self.xlabel = QtWidgets.QLabel(self.centralwidget)
        self.xlabel.setGeometry(QtCore.QRect(310, 90, 51, 20))
        self.xlabel.setObjectName("xlabel")
        self.ylabel = QtWidgets.QLabel(self.centralwidget)
        self.ylabel.setGeometry(QtCore.QRect(310, 130, 51, 20))
        self.ylabel.setObjectName("ylabel")
        self.zlabel = QtWidgets.QLabel(self.centralwidget)
        self.zlabel.setGeometry(QtCore.QRect(310, 170, 51, 20))
        self.zlabel.setObjectName("zlabel")
        self.poslabel = QtWidgets.QLabel(self.centralwidget)
        self.poslabel.setGeometry(QtCore.QRect(310, 30, 46, 16))
        self.poslabel.setObjectName("poslabel")
        self.posdisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.posdisplay.setGeometry(QtCore.QRect(360, 30, 151, 21))
        self.posdisplay.setObjectName("posdisplay")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stage Controls"))
        self.buttonforward.setText(_translate("MainWindow", "↑"))
        self.buttonleft.setText(_translate("MainWindow", "←"))
        self.buttonright.setText(_translate("MainWindow", "→"))
        self.buttondown.setText(_translate("MainWindow", "Down"))
        self.buttonback.setText(_translate("MainWindow", "↓"))
        self.buttonup.setText(_translate("MainWindow", "Up"))
        self.xlabel.setText(_translate("MainWindow", "mm per ↕:"))
        self.ylabel.setText(_translate("MainWindow", "mm per ↔:"))
        self.zlabel.setText(_translate("MainWindow", "mm per Z:"))
        self.poslabel.setText(_translate("MainWindow", "Position"))
