acquisition:
  base_directory: 'D:\'
  name_suffix: ''
  compress: True
  stimulus_file: ''
  ramp_seconds: 5
  recording_seconds: 10
  led_percent: 10
camera:
  recording_fps: 80
  preview_fps: 10
  gain: 1
  cam_trig_width_ms: 0.02
  ROI: #only in steps of 4
    y_size: 2048
    x_size: 2048
    y_decenter: 0
    x_decenter: 0
    y_bin: 1
    x_bin: 1 #=y_bin
psf:
  base_directory: 'D:\'
  name_suffix: ''
  z_layers: 40
  z_distance_mm: 0.005
  n_frames: 100
stage:
  type: 'standa' #"sutter"
  calibration:
  overshoot: 0.001
  preview_move_mm: 0.01
daq:
  rate: 50000
  device: 'Dev1'
  ao_channels: 'ao2'
  do_port: 'port0/line0'
  shutter_line: 'port0/line3'
  stim_channels: 'Dev2/ao0:3'
hardware:
  led_control_v: 5
alignment:
  window_size: [50, 50]
  edge_offset: [100, 100]
user_defined:
  notes: ''
  fish_orientation: [1, -1, 1]