acquisition:
  base_directory: 'D:\'
  name_suffix: ''
  compress: True
  stimulus_file: ''
  ramp_seconds: 0
  recording_seconds: 10
  led_percent: 100
  fps: 80
preview:
  fps: 10
stage:
  type: 'standa' #"sutter"
  calibration: [.0025, .0025, .005]
  overshoot: 0.001
psf:
  base_directory: 'D:\'
  name_suffix: ''
  z_layers: 120
  z_distance_mm: 0.025
  n_frames: 10
  fps: 2
camera:
  gain: 1
  cam_trig_width_ms: 0.05
  dtype: "uint8" #"uint16 and "uint8" supported
  ROI: #only in steps of 4
    y_size: 2048
    x_size: 2048
    y_decenter: 0
    x_decenter: 0
    y_bin: 1
    x_bin: 1 #=y_bin
daq:
  rate: 50000
  device: 'Dev1'
  ao_channels: 'ao2'
  do_port: 'port0/line0'
  shutter_line: 'port0/line3'
  stim_channels: 'Dev2/ao0:3'
hardware:
  led_control_v: 5
alignment:
  window_size: [50, 50]
  edge_offset: [100, 100]
user_defined:
  notes: ''
  fish_orientation: [1, -1, 1]